### ISSUE TITLE
Installation problems (Windows 10)

### ISSUE THREAD

**Issue by AlistairCurd** [NoldAndreas/FINDER#2]
Code sounds interesting from the paper!

I was unable to install the environment with conda following the instructions. This is in Windows 10.

Adding spaces around '~=' in requirements.txt got things going, but with a conda deprecation warning.
Changing to '=' (with or without spaces and removing the sub-subversion number removed the deprecation warning.

'h5p' was not found, so I tried changing this to 'h5py' in requirements.txt, and everything has installed now. Is that the package you meant, or is there a different one somewhere? There were some strange warnings about package sizes and checksums being wrong, but I don't know whether that could be a conda bug.

**Comment by NoldAndreas** [comment]
Hi, thanks a lot for reaching out! You are right, currently it does not work with conda. However it works with pip: 

'python3 -m venv finder_env    
source finder_env/bin/activate
pip install -r requirements.txt

The requirements-file contains the h5py package (not h5p), maybe this was changed after the download? 

In any case, we will update the readme-file shortly.

**Comment by NoldAndreas** [comment]
I just updated the file
