### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by AlistairCurd** [NoldAndreas/FINDER#3]
Both notebooks fail at the point of trying to load or find data. (After I added the Modules folder to the Python path in synthetic_data.ipynb - I added a cell to do this temporarily in my local copy of the repository.)

This seems to be because the data is not present in the locations specified in the notebooks. Can you help by including more instructions or the data, please?

Thanks.

**Comment by NoldAndreas** [comment]
Thanks a lot for pointing this out. We will send an update concerning how to get the data shortly.

**Comment by NoldAndreas** [comment]
I now added the data to the repository -- both notebooks should now run directly. I also added the modules folder to the notebook. Does this resolve the issue?

**Comment by AlistairCurd** [comment]
Yes, this works nicely. Thanks, very interesting!
