### ISSUE TITLE
from Finder import finder - cannot import name 'finder'

### ISSUE THREAD

**Issue by AlistairCurd** [NoldAndreas/FINDER#4]
So this command copied from real_data.ipynb does not work.

But from Finder import Finder does work, if that helps (this was the spelling for the class in Finder.py)

**Comment by NoldAndreas** [comment]
I think you forgot to include the command which does not work (?)

**Comment by AlistairCurd** [comment]
Hi Andreas,

Good to be in touch.

Sorry, I should have in included it again, not just in the title - The command that did not work was

from Finder import finder

But using from Finder import Finder instead fixes this, and then I was able to run the algorithm on my own data, which is interesting, thanks.

Can you explain how FINDER compares with OPTICS (e.g. in scikit-learn)?

Best wishes,

Alistair

**Comment by NoldAndreas** [comment]
I did not find any command in our code where "from Finder import finder" was used with lower case. Can you check again?

Concerning the difference to OPTICS: In essence, OPTICS dynamically adapts the clustering criteria to the density of the local neighbourhood of the points. This means it can detect variations with dense and less dense regions of the same image. Here, we assume that the conditions/ the background noise is uniform across the image, and propose a method to determine suitable global parameters for a given image.

**Comment by AlistairCurd** [comment]
Thanks. I can't find that command in the notebooks now, either. Maybe it was something I created or altered, sorry if so!
